# Generated by Django 2.0.5 on 2018-10-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cource', models.CharField(max_length=30)),
                ('regno', models.CharField(max_length=30)),
                ('mid', models.CharField(max_length=30)),
            ],
        ),
    ]
